# Generated by Django 4.2.11 on 2024-11-26 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('fin_prdt_cd', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dcls_month', models.DateField(blank=True, null=True)),
                ('fin_co_no', models.CharField(blank=True, max_length=10, null=True)),
                ('kor_co_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('fin_prdt_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('join_way', models.CharField(blank=True, max_length=255, null=True)),
                ('mtrt_int', models.CharField(blank=True, max_length=255, null=True)),
                ('spcl_cnd', models.CharField(blank=True, max_length=255, null=True)),
                ('join_deny', models.CharField(blank=True, max_length=255, null=True)),
                ('join_member', models.CharField(blank=True, max_length=255, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('max_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('dcls_strt_day', models.DateField(blank=True, null=True)),
                ('dcls_end_day', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('fin_prdt_cd', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dcls_month', models.DateField(blank=True, null=True)),
                ('fin_co_no', models.CharField(blank=True, max_length=10, null=True)),
                ('kor_co_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('fin_prdt_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('join_way', models.CharField(blank=True, max_length=255, null=True)),
                ('mtrt_int', models.CharField(blank=True, max_length=255, null=True)),
                ('spcl_cnd', models.CharField(blank=True, max_length=255, null=True)),
                ('join_deny', models.CharField(blank=True, max_length=255, null=True)),
                ('join_member', models.CharField(blank=True, max_length=255, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('max_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('dcls_strt_day', models.DateField(blank=True, null=True)),
                ('dcls_end_day', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingOption',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('dcls_month', models.DateField(blank=True, null=True)),
                ('fin_co_no', models.CharField(blank=True, max_length=10, null=True)),
                ('intr_rate_type', models.CharField(blank=True, max_length=255, null=True)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('rsrv_type', models.CharField(blank=True, max_length=255, null=True)),
                ('rsrv_type_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('intr_rate2', models.CharField(blank=True, max_length=255, null=True)),
                ('fin_prdt_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='fin_products.savingproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('dcls_month', models.DateField(blank=True, null=True)),
                ('fin_co_no', models.CharField(blank=True, max_length=10, null=True)),
                ('intr_rate_type', models.CharField(blank=True, max_length=255, null=True)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('intr_rate2', models.CharField(blank=True, max_length=255, null=True)),
                ('fin_prdt_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='fin_products.depositproduct')),
            ],
        ),
    ]
